### PR TITLE
WIP : reorganize and fix tests

### PR DESCRIPTION
**Pull request by cortner**
@munozariasjm - I'm rewriting tests in a way that makes them suitable for interactive debugging. I hope you are ok with that. 

I will now also try to fix CI

### CODE REVIEW

**Comment by cortner** [comment]
hah! found the culprit!!! There is a bug in `_get_data` which was hidden by the inbounds macro

**Comment by cortner** [comment]
last commit fixes some data reader problems

**Comment by cortner** [comment]
CI finally works!!

**Comment by munozariasjm** [comment]
This is great!

**Pull request merged**
